spring:
  datasource:
    #url: jdbc:h2:~/rent/rentshop
    url : jdbc:h2:tcp://localhost/~/rentshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create


#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100