spring:
  datasource:
    #url: jdbc:h2:~/rent/rentshop
    url : jdbc:h2:tcp://localhost/~/rentshop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create